name: deployment
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: deploy website
        runs-on: ubuntu-latest
        steps:
            - name: create ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H aldenluth.fi > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh root@aldenluth.fi "cd aldenluthfi/src/django-web && docker stop $(docker ps -a -q); docker system prune -a -f && docker-compose -d --build"
            - name: cleanup
              run: rm -rf ~/.ssh